services:
  radioMysql:
    image: mysql
    container_name: appMysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3311:3306
    networks:
      - AppNetwork
    env_file:
      - .env
    volumes:
      - supply_chain_mysql_data:/var/lib/mysql

  App:
    image: node:20.15.1
    container_name: appCT
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 3449:3000
    env_file:
      - .env
    command: sh -c "npm i && npx prisma migrate dev && npx prisma db pull && npx next dev"
    # command: sh -c "npm install && npm run db:migrate && npm run build && npm run start"
    # command: sh -c "npm install && npm run db:migrate && npm run build && npm run start"
    restart: unless-stopped
    depends_on:
      - radioMysql
    networks:
      - AppNetwork

volumes:
  supply_chain_mysql_data:

networks:
  AppNetwork: