[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.0",
    "python-dotenv>=1.1.1",
    "smolagents[litellm,toolkit]>=1.19.0",
    "sqlalchemy>=2.0.41",
]
